config/routes.rb
Blog::Application.routes.draw do
  devise_for :users
  get "welcome/index"

  resources :posts do
    resources :comments, only: [:new, :create]
    resources :votes
  end

  root to: 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments
  has_many :votes

  validates :title, presence: true,
    length: {minimum: 2}

  def votes_total
    return nil if (upvotes + downvotes).empty?
    upvotes.size - downvotes.size
  end

  def self.sorted_by_votes
    all.sort_by { |p| p.votes_total || 0 }.reverse
  end

  private

    def upvotes
      votes.up
    end

    def downvotes
      votes.down
    end

end 

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :post
  scope :up, -> { where(direction: 'up') }
  scope :down, -> { where(direction: 'down')}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @post.comments.create(params[:comment].permit(:body))
    redirect_to @post
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.sorted_by_votes
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new params[:post].permit(:title, :body)

    if @post.save
      flash[:notice] = "Post saved"
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    puts params.inspect
    @post = Post.find(params[:post_id])
    @post.votes.create(direction: params[:direction])
    render json: { id: @post.id, votes: @post.votes_total }
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def vote_button post, direction, link_text
    button_to link_text, post_votes_path(post, direction: direction, format: :json), remote: true
  end

end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<ul>
  <% @post.comments.each do |comment| %>
    <li><p><%= comment.body %></p></li>
  <% end %>
</ul>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <%= f.text_area :body, placeholder: 'Add a comment' %><br/>
    <%= f.submit 'Post comment' %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nadia learns Rails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
    <ul class="hmenu">
      <%= render 'devise/menu/registration_items' %>
      <%= render 'devise/menu/login_items' %>
    </ul>
    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
  <p>
    <%= f.submit 'Save post' %>
  </p>
<% end %>

app/views/posts/_post.html.erb
<% @posts.each do |post| %>
  <div class="post_item">
    <h2><%= link_to post.title, post, :class => "post_title" %></h2>
    <p><%=post.body %></p>
    <p><%= post.created_at.strftime('%H:%M %d/%m/%g') %></p>

    <h4 class="votes-count" data-id='<%= post.id %>' data-votes-count='<%= post.votes_total %>'><%= post.votes_total %></h4>
    <%= vote_button post, 'up', '⬆' %>
    <%= vote_button post, 'down', '⬇' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h3>Edit post</h3>

<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag "posts" %>

<div class="header">
  <%= link_to 'Homepage', welcome_index_path, :class => "homepage" %>
  <%= link_to 'New post', new_post_path, :class => "new_post_button" %>
</div>

<h1 class="post_heading">Posts</h1>

<%= flash[:notice] %>

<%= render 'post' %>

app/views/posts/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong><%= @post.title %></strong>
</p>

<p>
  <%= @post.body %>
</p>


<h4>Comments</h4>

<%= pluralize @post.comments.count, 'comment' %>

<%= render 'comments/comment' %>
<%= render 'comments/form' %>

<br/>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure you want to delete this post?'} %> | 
<%= link_to 'Back', controller: "posts" %>

app/views/welcome/index.html.erb
<h1 class="welcome">Nadia learns Rails!</h1>

<%= link_to "Enter", controller: "posts" %>